services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow-init:
    hostname: airflow-init
    build:
      context: .
      dockerfile: airflow/Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey123"
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
      AIRFLOW__LOGGING__REMOTE_LOGGING: False
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: 8793
      AIRFLOW_CONN_ELASTICSEARCH_DEFAULT: http://clustersdaelatsic.eastus.cloudapp.azure.com:9200
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    entrypoint: >
      bash -c "
        airflow db upgrade &&
        airflow users create --username tidiani --firstname tidiani --lastname top --role Admin --email catidiani.top@univ-thies.sn --password password
      "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./kafka:/opt/airflow/kafka
      - ./kafka/utils:/opt/airflow/kafka/utils
      - ./logs:/opt/airflow/logs
    restart: on-failure

  airflow-webserver:
    hostname: airflow-webserver
    build:
      context: .
      dockerfile: airflow/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey123"
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
      AIRFLOW__LOGGING__REMOTE_LOGGING: False
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: 8793
      AIRFLOW_CONN_ELASTICSEARCH_DEFAULT: http://clustersdaelatsic.eastus.cloudapp.azure.com:9200
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      KAFKA_BROKER: kfakasda.eastus.cloudapp.azure.com:9092
      ELASTIC_HOST: http://clustersdaelatsic.eastus.cloudapp.azure.com:9200
      ELASTIC_USER: elastic
      ELASTIC_PASS: changeme
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./kafka:/opt/airflow/kafka
      - ./kafka/utils:/opt/airflow/kafka/utils
      - ./logs:/opt/airflow/logs
    command: webserver

  airflow-scheduler:
    hostname: airflow-scheduler
    build:
      context: .
      dockerfile: airflow/Dockerfile
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8083:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey123"
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
      AIRFLOW__LOGGING__REMOTE_LOGGING: False
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: 8793
      AIRFLOW_CONN_ELASTICSEARCH_DEFAULT: http://clustersdaelatsic.eastus.cloudapp.azure.com:9200
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      KAFKA_BROKER: kfakasda.eastus.cloudapp.azure.com:9092
      ELASTIC_HOST: http://clustersdaelatsic.eastus.cloudapp.azure.com:9200
      ELASTIC_USER: elastic
      ELASTIC_PASS: changeme
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./kafka:/opt/airflow/kafka
      - ./kafka/utils:/opt/airflow/kafka/utils
      - ./logs:/opt/airflow/logs
    command: scheduler

  kafka-producer:
    build:
      context: .
      dockerfile: kafka/Dockerfile
    depends_on:
      - airflow-scheduler
    volumes:
      - ./data:/data
      - ./kafka:/app
      - ./kafka/utils:/app/kafka/utils
    environment:
      KAFKA_BROKER: kfakasda.eastus.cloudapp.azure.com:9092

volumes:
  postgres-data:
