services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      KAFKA_BROKER: kfakasda.eastus.cloudapp.azure.com:9092
      ELASTIC_HOST: http://clustersdaelatsic.eastus.cloudapp.azure.com:9200
      ELASTIC_USER: elastic
      ELASTIC_PASS: changeme
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./kafka:/opt/airflow/kafka
      - ./kafka/utils:/opt/airflow/kafka/utils
    entrypoint: >
      bash -c "
        airflow db upgrade &&
        airflow users create --username tidiani --firstname tidiani --lastname top --role Admin --email catidiani.top@univ-thies.sn --password password &&
        exec airflow webserver
      "
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      KAFKA_BROKER: kfakasda.eastus.cloudapp.azure.com:9092
      ELASTIC_HOST: http://clustersdaelatsic.eastus.cloudapp.azure.com:9200
      ELASTIC_USER: elastic
      ELASTIC_PASS: changeme
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./kafka:/opt/airflow/kafka
      - ./kafka/utils:/opt/airflow/kafka/utils
    entrypoint: bash -c "airflow db upgrade && exec airflow scheduler"
    command: scheduler

  kafka-producer:
    build:
      context: .
      dockerfile: kafka/Dockerfile
    depends_on:
      - airflow-scheduler
    volumes:
      - ./data:/data
      - ./kafka:/app
      - ./kafka/utils:/app/kafka/utils
    environment:
      KAFKA_BROKER: kfakasda.eastus.cloudapp.azure.com:9092

volumes:
  postgres-data:
